# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
puts 'Cleaning database...'
# Facility.destroy_all

puts '🌱 Seeding facilities in Mauritius...'

facilities = [
  { name: "Victoria", address: "Quatre Bornes, Mauritius", phone_number: "4253031", facility_type: "Hospital" },
  { name: "Jeevanjee Hospital", address: "Port Louis, Mauritius", phone_number: "2031002", facility_type: "Hospital" },
  { name: "Wellkin Hospital", address: "Moka, Mauritius", phone_number: "6051000", facility_type: "Hospital" },
  { name: "MedPoint Clinic", address: "Grand Baie, Mauritius", phone_number: "4267777", facility_type: "Clinic" },
  { name: "C-Care Darné", address: "Floréal, Mauritius", phone_number: "6012300", facility_type:"Clinic" },
  { name: "C-Care Moka", address: "Royal Road, Moka, Mauritius", phone_number: "6051000", facility_type: "Clinic" },
  { name: "C-Care Tamarin", address: "Tamarin, Mauritius", phone_number: "4601900", facility_type: "Clinic" },
  { name: "Clinique du Nord", address: "Grand Baie, Mauritius", phone_number: "2472532", facility_type: "Clinic" },
  { name: "Victoria Clinic", address: "Quatre Bornes, Mauritius", phone_number: "4020800", facility_type: "Clinic" },
  { name: "Jeetoo Hospital", address: "Port Louis, Mauritius", phone_number: "2031001", facility_type: "Hospital" },
  { name: "Sun Medical Clinic", address: "Curepipe, Mauritius", phone_number: "6061300", facility_type: "Clinic" },
  { name: "Artemis Curepipe Hospital", address: "Curepipe,", phone_number: "6515050", facility_type: "Clinic" },
  { name: "C-Care Grand Baie", address: "Grand Baie, Mauritius", phone_number: "6012500", facility_type: "Clinic" },
  { name: "Premium Care Clinic", address: "Vacoas, Mauritius", phone_number: "4908128", facility_type: "Clinic" },
  { name: "Nirvaran Clinic", address: "Quatre Bornes, Mauritius", phone_number: "55063945", facility_type: "Clinic" },
  { name: "Clinique Ferrière", address: "Curepipe, Mauritius", phone_number: "6763332", facility_type: "Clinic" },
  { name: "Jawaharlal Nehru", address: "Rose Belle, Mauritius", phone_number: "6037000", facility_type: "Hospital" },
  { name: "RightNow Medical Hub", address: "Curepipe, Mauritius", phone_number: "54794843", facility_type: "Clinic" },
  { name: "City Clinic", address: "Port Louis, Mauritius", phone_number: "2011600", facility_type: "Clinic" },
  { name: "Medic World", address: "Quatre Bornes, Mauritius", phone_number: "4073000", facility_type: "Clinic" },
  { name: "Clinique Muller", address: "Curepipe, Mauritius", phone_number: "6702911", facility_type: "Clinic" },
  { name: "Phoenix Health Centre", address: "Vacoas, Mauritius", phone_number: "6964286", facility_type: "Clinic" },
  { name: "Rose Hill Centre", address: "Rose Hill, Mauritius", phone_number: "4541937", facility_type: "Clinic" },
  { name: "Medical Surgical Centre", address: "Floreal, Mauritius", phone_number: "6012300", facility_type: "Clinic" },
  { name: "Forest-Side Health Center", address: "Mauritius", phone_number: "6742647", facility_type: "Clinic" },
  { name: "Holyrood Community Centre", address: "Vacoas, Mauritius", phone_number: "6973073", facility_type: "Clinic" },
  { name: "Mahebourg Hospital", address: "Mahebourg, Mauritius", phone_number: "6042000", facility_type: "Hospital" },
  { name: "Eagle Clinic", address: "Central Flacq, Mauritius", phone_number: "4605500", facility_type: "Clinic" },
  { name: "Lady Sushil Ramgoolam", address: "Belveder, Mauritius", phone_number: "4181364", facility_type: "Clinic" }
]

facilities.each do |facility|
  Facility.create!(facility)
end

puts "✅ Done seeding!"

users = [
  {
    user_id: "user 001",
    first_name: "John",
    last_name: "Doe",
    date_of_birth: "1985-03-15",
    email: "john.doe@example.com",
    password: "password123",
    phone_number: "52512345",
    address: "Quatre Bornes, Mauritius"
  },
  {
    user_id: "user 002",
    first_name: "Sarah",
    last_name: "Ramsamy",
    date_of_birth: "1990-07-22",
    email: "sarah.ramsamy@example.com",
    password: "password123",
    phone_number: "58023456",
    address: "Port Louis, Mauritius"
  },
  {
    user_id: "user 003",
    first_name: "Kevin",
    last_name: "Pillay",
    date_of_birth: "1995-01-10",
    email: "kevin.pillay@example.com",
    password: "password123",
    phone_number: "59098765",
    address: "Curepipe, Mauritius"
  },
  {
    user_id: "user 004",
    first_name: "Anjali",
    last_name: "Kumar",
    date_of_birth: "1988-04-05",
    email: "anjali.kumar@example.com",
    password: "password123",
    phone_number: "59876543",
    address: "Rose Hill, Mauritius"
  },
  {
    user_id: "user 005",
    first_name: "Rakesh",
    last_name: "Singh",
    date_of_birth: "1979-12-19",
    email: "rakesh.singh@example.com",
    password: "password123",
    phone_number: "52654321",
    address: "Vacoas, Mauritius"
  },
  {
    user_id: "user 006",
    first_name: "Priya",
    last_name: "Nath",
    date_of_birth: "1992-11-11",
    email: "priya.nath@example.com",
    password: "password123",
    phone_number: "53456789",
    address: "Grand Baie, Mauritius"
  },
  {
    user_id: "user 007",
    first_name: "Arjun",
    last_name: "Patel",
    date_of_birth: "1983-06-25",
    email: "arjun.patel@example.com",
    password: "password123",
    phone_number: "54781234",
    address: "Flic en Flac, Mauritius"
  },
  {
    user_id: "user 008",
    first_name: "Leela",
    last_name: "Reddy",
    date_of_birth: "1996-09-17",
    email: "leela.reddy@example.com",
    password: "password123",
    phone_number: "55098765",
    address: "Mahebourg, Mauritius"
  },
  {
    user_id: "user 009",
    first_name: "Vikram",
    last_name: "Shah",
    date_of_birth: "1987-05-30",
    email: "vikram.shah@example.com",
    password: "password123",
    phone_number: "56012345",
    address: "Curepipe, Mauritius"
  },
  {
    user_id: "user 010",
    first_name: "Anita",
    last_name: "Chowdhury",
    date_of_birth: "1991-03-08",
    email: "anita.chowdhury@example.com",
    password: "password123",
    phone_number: "57890123",
    address: "Port Louis, Mauritius"
  },
  {
    user_id: "user 011",
    first_name: "Rohan",
    last_name: "Maharaj",
    date_of_birth: "1989-08-21",
    email: "rohan.maharaj@example.com",
    password: "password123",
    phone_number: "58765432",
    address: "Quatre Bornes, Mauritius"
  },
  {
    user_id: "user 012",
    first_name: "Nisha",
    last_name: "Dewan",
    date_of_birth: "1993-12-14",
    email: "nisha.dewan@example.com",
    password: "password123",
    phone_number: "59987654",
    address: "Grand Baie, Mauritius"
  },
  {
    user_id: "user 013",
    first_name: "Sanjay",
    last_name: "Bhandari",
    date_of_birth: "1981-02-02",
    email: "sanjay.bhandari@example.com",
    password: "password123",
    phone_number: "52345678",
    address: "Rose Hill, Mauritius"
  },
  {
    user_id: "user 014",
    first_name: "Meena",
    last_name: "Varma",
    date_of_birth: "1986-07-07",
    email: "meena.varma@example.com",
    password: "password123",
    phone_number: "53678901",
    address: "Vacoas, Mauritius"
  },
  {
    user_id: "user 015",
    first_name: "Aditya",
    last_name: "Singh",
    date_of_birth: "1994-04-28",
    email: "aditya.singh@example.com",
    password: "password123",
    phone_number: "54901234",
    address: "Flic en Flac, Mauritius"
  },
  {
    user_id: "user 016",
    first_name: "Priyanka",
    last_name: "Rai",
    date_of_birth: "1990-11-03",
    email: "priyanka.rai@example.com",
    password: "password123",
    phone_number: "55234567",
    address: "Curepipe, Mauritius"
  },
  {
    user_id: "user 017",
    first_name: "Rajesh",
    last_name: "Sharma",
    date_of_birth: "1982-06-15",
    email: "rajesh.sharma@example.com",
    password: "password123",
    phone_number: "56789012",
    address: "Mahebourg, Mauritius"
  },
  {
    user_id: "user 018",
    first_name: "Sunita",
    last_name: "Kapoor",
    date_of_birth: "1995-09-09",
    email: "sunita.kapoor@example.com",
    password: "password123",
    phone_number: "57654321",
    address: "Grand Baie, Mauritius"
  },
  {
    user_id: "user 019",
    first_name: "Manish",
    last_name: "Gupta",
    date_of_birth: "1984-12-20",
    email: "manish.gupta@example.com",
    password: "password123",
    phone_number: "58345678",
    address: "Port Louis, Mauritius"
  },
  {
    user_id: "user 020",
    first_name: "Kavita",
    last_name: "Chopra",
    date_of_birth: "1987-03-30",
    email: "kavita.chopra@example.com",
    password: "password123",
    phone_number: "59012345",
    address: "Quatre Bornes, Mauritius"
  },
  {
    user_id: "user 021",
    first_name: "Amit",
    last_name: "Desai",
    date_of_birth: "1988-08-18",
    email: "amit.desai@example.com",
    password: "password123",
    phone_number: "59876543",
    address: "Rose Hill, Mauritius"
  },
  {
    user_id: "user 022",
    first_name: "Rina",
    last_name: "Patel",
    date_of_birth: "1991-05-12",
    email: "rina.patel@example.com",
    password: "password123",
    phone_number: "50765432",
    address: "Vacoas, Mauritius"
  },
  {
    user_id: "user 023",
    first_name: "Vijay",
    last_name: "Nair",
    date_of_birth: "1983-01-25",
    email: "vijay.nair@example.com",
    password: "password123",
    phone_number: "51234567",
    address: "Curepipe, Mauritius"
  },
  {
    user_id: "user 024",
    first_name: "Nandini",
    last_name: "Rao",
    date_of_birth: "1996-10-11",
    email: "nandini.rao@example.com",
    password: "password123",
    phone_number: "51987654",
    address: "Flic en Flac, Mauritius"
  },
  {
    user_id: "user 025",
    first_name: "Harish",
    last_name: "Mehta",
    date_of_birth: "1980-07-03",
    email: "harish.mehta@example.com",
    password: "password123",
    phone_number: "52345679",
    address: "Grand Baie, Mauritius"
  },
  {
    user_id: "user 026",
    first_name: "Pooja",
    last_name: "Sharma",
    date_of_birth: "1992-02-28",
    email: "pooja.sharma@example.com",
    password: "password123",
    phone_number: "53098765",
    address: "Mahebourg, Mauritius"
  },
  {
    user_id: "user 027",
    first_name: "Raj",
    last_name: "Chand",
    date_of_birth: "1985-09-14",
    email: "raj.chand@example.com",
    password: "password123",
    phone_number: "54012345",
    address: "Quatre Bornes, Mauritius"
  }
]
blood_requests = [
  {
    blood_request_id: "BR001",
    user_id: "user 001",
    facility_id: 1,
    blood_type: "A+",
    needed_by: "2025-12-01",
    status: "completed",
    patient_name: "John Doe",
    patient_phone_number: "52510001",
    message: "Scheduled transfusion",
    quantity: 2,
    created_at: Time.now - 5.days,
    completed_at: Time.now - 2.days
  },
  {
    blood_request_id: "BR002",
    user_id: "user 002",
    facility_id: 2,
    blood_type: "O-",
    needed_by: "2025-12-02",
    status: "pending",
    patient_name: "Sarah Ramsamy",
    patient_phone_number: "52510002",
    message: "Urgent transfusion needed",
    quantity: 1,
    created_at: Time.now - 3.days,
    completed_at: nil
  },
  {
    blood_request_id: "BR003",
    user_id: "user 003",
    facility_id: 3,
    blood_type: "B+",
    needed_by: "2025-12-03",
    status: "completed",
    patient_name: "Kevin Pillay",
    patient_phone_number: "52510003",
    message: "Scheduled transfusion",
    quantity: 3,
    created_at: Time.now - 6.days,
    completed_at: Time.now - 1.day
  },
  {
    blood_request_id: "BR004",
    user_id: "user 004",
    facility_id: 4,
    blood_type: "AB-",
    needed_by: "2025-12-04",
    status: "pending",
    patient_name: "Anjali Kumar",
    patient_phone_number: "52510004",
    message: "Emergency surgery",
    quantity: 1,
    created_at: Time.now - 2.days,
    completed_at: nil
  },
  {
    blood_request_id: "BR005",
    user_id: "user 005",
    facility_id: 5,
    blood_type: "O+",
    needed_by: "2025-12-05",
    status: "completed",
    patient_name: "Rakesh Singh",
    patient_phone_number: "52510005",
    message: "Routine transfusion",
    quantity: 2,
    created_at: Time.now - 7.days,
    completed_at: Time.now - 3.days
  },
  {
    blood_request_id: "BR006",
    user_id: "user 006",
    facility_id: 6,
    blood_type: "A-",
    needed_by: "2025-12-06",
    status: "pending",
    patient_name: "Priya Nath",
    patient_phone_number: "52510006",
    message: "Urgent requirement",
    quantity: 1,
    created_at: Time.now - 1.day,
    completed_at: nil
  },
  {
    blood_request_id: "BR007",
    user_id: "user 007",
    facility_id: 7,
    blood_type: "B-",
    needed_by: "2025-12-07",
    status: "completed",
    patient_name: "Arjun Patel",
    patient_phone_number: "52510007",
    message: "Scheduled surgery",
    quantity: 2,
    created_at: Time.now - 4.days,
    completed_at: Time.now - 2.days
  },
  {
    blood_request_id: "BR008",
    user_id: "user 008",
    facility_id: 8,
    blood_type: "AB+",
    needed_by: "2025-12-08",
    status: "pending",
    patient_name: "Leela Reddy",
    patient_phone_number: "52510008",
    message: "Accident case",
    quantity: 1,
    created_at: Time.now - 2.days,
    completed_at: nil
  },
  {
    blood_request_id: "BR009",
    user_id: "user 009",
    facility_id: 9,
    blood_type: "O-",
    needed_by: "2025-12-09",
    status: "completed",
    patient_name: "Vikram Shah",
    patient_phone_number: "52510009",
    message: "Routine transfusion",
    quantity: 2,
    created_at: Time.now - 6.days,
    completed_at: Time.now - 3.days
  },
  {
    blood_request_id: "BR010",
    user_id: "user 010",
    facility_id: 10,
    blood_type: "A+",
    needed_by: "2025-12-10",
    status: "pending",
    patient_name: "Anita Chowdhury",
    patient_phone_number: "52510010",
    message: "Emergency surgery",
    quantity: 1,
    created_at: Time.now - 1.day,
    completed_at: nil
  },
  {
    blood_request_id: "BR011",
    user_id: "user 011",
    facility_id: 11,
    blood_type: "B+",
    needed_by: "2025-12-11",
    status: "completed",
    patient_name: "Rohan Maharaj",
    patient_phone_number: "52510011",
    message: "Post-surgery",
    quantity: 3,
    created_at: Time.now - 7.days,
    completed_at: Time.now - 5.days
  },
  {
    blood_request_id: "BR012",
    user_id: "user 012",
    facility_id: 12,
    blood_type: "AB-",
    needed_by: "2025-12-12",
    status: "pending",
    patient_name: "Nisha Dewan",
    patient_phone_number: "52510012",
    message: "Urgent transfusion",
    quantity: 1,
    created_at: Time.now - 1.day,
    completed_at: nil
  },
  {
    blood_request_id: "BR013",
    user_id: "user 013",
    facility_id: 13,
    blood_type: "O+",
    needed_by: "2025-12-13",
    status: "completed",
    patient_name: "Sanjay Bhandari",
    patient_phone_number: "52510013",
    message: "Scheduled transfusion",
    quantity: 2,
    created_at: Time.now - 3.days,
    completed_at: Time.now - 1.day
  },
  {
    blood_request_id: "BR014",
    user_id: "user 014",
    facility_id: 14,
    blood_type: "A-",
    needed_by: "2025-12-14",
    status: "pending",
    patient_name: "Meena Varma",
    patient_phone_number: "52510014",
    message: "Accident case",
    quantity: 1,
    created_at: Time.now - 2.days,
    completed_at: nil
  },
  {
    blood_request_id: "BR015",
    user_id: "user 015",
    facility_id: 15,
    blood_type: "B-",
    needed_by: "2025-12-15",
    status: "completed",
    patient_name: "Aditya Singh",
    patient_phone_number: "52510015",
    message: "Scheduled surgery",
    quantity: 2,
    created_at: Time.now - 4.days,
    completed_at: Time.now - 2.days
  },
  {
    blood_request_id: "BR016",
    user_id: "user 016",
    facility_id: 16,
    blood_type: "AB+",
    needed_by: "2025-12-16",
    status: "pending",
    patient_name: "Priyanka Rai",
    patient_phone_number: "52510016",
    message: "Urgent transfusion",
    quantity: 1,
    created_at: Time.now - 1.day,
    completed_at: nil
  },
  {
    blood_request_id: "BR017",
    user_id: "user 017",
    facility_id: 17,
    blood_type: "O-",
    needed_by: "2025-12-17",
    status: "completed",
    patient_name: "Rajesh Sharma",
    patient_phone_number: "52510017",
    message: "Post-surgery",
    quantity: 2,
    created_at: Time.now - 5.days,
    completed_at: Time.now - 2.days
  },
  {
    blood_request_id: "BR018",
    user_id: "user 018",
    facility_id: 18,
    blood_type: "A+",
    needed_by: "2025-12-18",
    status: "pending",
    patient_name: "Sunita Kapoor",
    patient_phone_number: "52510018",
    message: "Emergency transfusion",
    quantity: 1,
    created_at: Time.now - 1.day,
    completed_at: nil
  },
  {
    blood_request_id: "BR019",
    user_id: "user 019",
    facility_id: 19,
    blood_type: "B+",
    needed_by: "2025-12-19",
    status: "completed",
    patient_name: "Manish Gupta",
    patient_phone_number: "52510019",
    message: "Scheduled transfusion",
    quantity: 3,
    created_at: Time.now - 6.days,
    completed_at: Time.now - 3.days
  },
  {
    blood_request_id: "BR020",
    user_id: "user 020",
    facility_id: 20,
    blood_type: "AB-",
    needed_by: "2025-12-20",
    status: "pending",
    patient_name: "Kavita Chopra",
    patient_phone_number: "52510020",
    message: "Urgent requirement",
    quantity: 1,
    created_at: Time.now - 2.days,
    completed_at: nil
  },
  {
    blood_request_id: "BR021",
    user_id: "user 021",
    facility_id: 21,
    blood_type: "O+",
    needed_by: "2025-12-21",
    status: "completed",
    patient_name: "Amit Desai",
    patient_phone_number: "52510021",
    message: "Routine transfusion",
    quantity: 2,
    created_at: Time.now - 7.days,
    completed_at: Time.now - 4.days
  },
  {
    blood_request_id: "BR022",
    user_id: "user 022",
    facility_id: 22,
    blood_type: "A-",
    needed_by: "2025-12-22",
    status: "pending",
    patient_name: "Rina Patel",
    patient_phone_number: "52510022",
    message: "Emergency case",
    quantity: 1,
    created_at: Time.now - 1.day,
    completed_at: nil
  },
  {
    blood_request_id: "BR023",
    user_id: "user 023",
    facility_id: 23,
    blood_type: "B-",
    needed_by: "2025-12-23",
    status: "completed",
    patient_name: "Vijay Nair",
    patient_phone_number: "52510023",
    message: "Scheduled surgery",
    quantity: 2,
    created_at: Time.now - 5.days,
    completed_at: Time.now - 2.days
  },
  {
    blood_request_id: "BR024",
    user_id: "user 024",
    facility_id: 24,
    blood_type: "AB+",
    needed_by: "2025-12-24",
    status: "pending",
    patient_name: "Nandini Rao",
    patient_phone_number: "52510024",
    message: "Urgent transfusion",
    quantity: 1,
    created_at: Time.now - 1.day,
    completed_at: nil
  },
  {
    blood_request_id: "BR025",
    user_id: "user 025",
    facility_id: 25,
    blood_type: "O-",
    needed_by: "2025-12-25",
    status: "completed",
    patient_name: "Harish Mehta",
    patient_phone_number: "52510025",
    message: "Routine transfusion",
    quantity: 2,
    created_at: Time.now - 6.days,
    completed_at: Time.now - 3.days
  },
  {
    blood_request_id: "BR026",
    user_id: "user 026",
    facility_id: 26,
    blood_type: "A+",
    needed_by: "2025-12-26",
    status: "pending",
    patient_name: "Pooja Sharma",
    patient_phone_number: "52510026",
    message: "Accident case",
    quantity: 1,
    created_at: Time.now - 2.days,
    completed_at: nil
  },
  {
    blood_request_id: "BR027",
    user_id: "user 027",
    facility_id: 27,
    blood_type: "B+",
    needed_by: "2025-12-27",
    status: "completed",
    patient_name: "Raj Chand",
    patient_phone_number: "52510027",
    message: "Scheduled transfusion",
    quantity: 2,
    created_at: Time.now - 3.days,
    completed_at: Time.now - 1.day
  }
]
